---

- hosts: all
  become: true
  tasks:

  - name: install apache and php
    package:  # agnostic package manager; will be substituted by local PK based on distro.
    # https://docs.ansible.com/ansible/latest/modules/package_module.html
      name: 
        - "{{ apache_pack }}" 
        - "{{ php_pack }}"
      state: latest
      update_cache: yes
